### ISSUE TITLE
Fix large range of sections

### ISSUE THREAD

**Issue by eddyod** [eddyod/pipeline_utility#5]
Bili,
If you run this script in the atlas dir: 
python create_pointvolume.py --src_animal DK39 --dst_animal DK52 --create False --layer "premotor"

The x and y coordinates look fine but the range of the z/section is way too large. Can you fix this script?
Thanks,

**Comment by eddyod** [comment]
DK39 and DK52 premotor should be overlapping much more than what they are currently. The points in DK39 are actually falling outside the boundary of the brain and they, of course, need to be inside the brain boundary. This fix will be important for use in other brains.

**Comment by qobilidop** [comment]
Hi Ed,

From what I read from the code, this script is aligning one brain to another. I wonder if we want to do this, or if we want to align both brains to the atlas and bring both brains to the atlas space? I might be wrong, but I think what we want to do is the following:

1. Align atlas to brain1 and get the transformation (R1, t1).
2. Align atlas to brain2 and get the transformation (R2, t2).
3. Then, if we want to transform a set of points from brain1 space to brain2 space, we use the transformation (R2 * R1^-1, t2 - t1), instead of doing another alignment.

**Comment by qobilidop** [comment]
I've made [a notebook](https://github.com/eddyod/pipeline_utility/blob/master/Bili/2020-11-25_transform-points-between-brains.ipynb) to demonstrate the core process of this coordinate transformation. If you modify the script accordingly, I believe it shall work as expected. There are some details in the script that I don't understand so I didn't modify the script directly.

**Comment by eddyod** [comment]
I updated that script and reran it. Can you take a look at the results,

Altas, DK39premotor, DK52 PM Nucleus
--


I'll show Beth on Wednesday as neither of us can really tell for sure.

**Comment by eddyod** [comment]
@qobilidop 
We need to change the REST API to align layers to the atlas. So instead of aligning DK52 to DK39, we will just align DK52 to the atlas and then DK39 to the atlas.
Can you create a new script or notebook like:
pipeline_utility/Bili/2020-10-31_dk52-automatic-alignment.ipynb
The script should get the animal from the argparse.
Query the sql for centers of mass for that brain and then get the rotation/translation to align that brain to the atlas.
This script should work for any brain that has data in the centers of mass table.

**Comment by qobilidop** [comment]
If I understand it correctly, what we want is the reverse transformation from what we already have? A quick solution is to just invert the matrix instead of doing another alignment. Say we could get `r`, `t_scaled` from `https://activebrainatlas.ucsd.edu/activebrainatlas/alignatlas?animal=DK52`, what they represent is the forward transformation:
```python
t = t_scaled * scale_image  # scale_image = np.array([[0.325, 0.325, 20]]).T
x_image = r @ x_atlas + t
```

So the reverse transformation is:
```python
x_atlas = r^-1 @ x_image - r^-1 @ t  # r^-1 = np.linalg.inv(r)
r_inv = r^-1
t_inv = - r^-1 @ t
t_inv_scaled = t_inv / scale_atlas = - r^-1 @ (t_scaled * scale_image) / scale_atlas  # scale_atlas = np.array([[10, 10, 20]]).T
```

The new API could report `r_inv` and `t_inv_scaled` for neuroglancer to use.

**Comment by eddyod** [comment]
@qobilidop 
Instead of doing the above, it was easier just to change this code:
        # align atlas to animal, original code
        #src_point_set = np.array([atlas_centers[s] for s in structures]).T
        #src_point_set = np.diag(atlas_box_scales) @ src_point_set
        #dst_point_set = np.array([reference_centers[s] for s in structures]).T
        #dst_point_set = np.diag(reference_scales) @ dst_point_set
        # align animal to atlas, new code
        dst_point_set = np.array([atlas_centers[s] for s in structures]).T
        dst_point_set = np.diag(atlas_box_scales) @ dst_point_set
        src_point_set = np.array([reference_centers[s] for s in structures]).T
        src_point_set = np.diag(reference_scales) @ src_point_set

Let me know if that is wrong but the results look good. I'll show you Wednesday.

**Comment by qobilidop** [comment]
> @qobilidop
> Instead of doing the above, it was easier just to change this code:
> # align atlas to animal, original code
> #src_point_set = np.array([atlas_centers[s] for s in structures]).T
> #src_point_set = np.diag(atlas_box_scales) @ src_point_set
> #dst_point_set = np.array([reference_centers[s] for s in structures]).T
> #dst_point_set = np.diag(reference_scales) @ dst_point_set
> # align animal to atlas, new code
> dst_point_set = np.array([atlas_centers[s] for s in structures]).T
> dst_point_set = np.diag(atlas_box_scales) @ dst_point_set
> src_point_set = np.array([reference_centers[s] for s in structures]).T
> src_point_set = np.diag(reference_scales) @ src_point_set
> 
> Let me know if that is wrong but the results look good. I'll show you Wednesday.

That's great! This looks correct to me.
